/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    items: Item;
    categories: Category;
    orders: Order;
    reviews: Review;
    'abandoned-carts': AbandonedCart;
    'delivery-settings': DeliverySetting;
    posts: Post;
    'program-participants': ProgramParticipant;
    coupons: Coupon;
    'push-subscriptions': PushSubscription;
    wishlists: Wishlist;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    items: ItemsSelect<false> | ItemsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    'abandoned-carts': AbandonedCartsSelect<false> | AbandonedCartsSelect<true>;
    'delivery-settings': DeliverySettingsSelect<false> | DeliverySettingsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'program-participants': ProgramParticipantsSelect<false> | ProgramParticipantsSelect<true>;
    coupons: CouponsSelect<false> | CouponsSelect<true>;
    'push-subscriptions': PushSubscriptionsSelect<false> | PushSubscriptionsSelect<true>;
    wishlists: WishlistsSelect<false> | WishlistsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Primary contact number for orders and updates
   */
  customerNumber?: string | null;
  /**
   * Used to compute delivery charges automatically.
   */
  deliveryZone: 'inside_dhaka' | 'outside_dhaka';
  role: 'admin' | 'user';
  firstName: string;
  lastName: string;
  /**
   * Shipping address used for orders
   */
  address?: {
    line1?: string | null;
    line2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Optional. Provide descriptive text for accessibility when available.
   */
  alt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "items".
 */
export interface Item {
  id: number;
  name: string;
  /**
   * Unique product SKU/barcode for inventory tracking
   */
  sku?: string | null;
  /**
   * Shown on product highlights and cards.
   */
  shortDescription?: string | null;
  /**
   * Main product copy displayed on the item page.
   */
  description: string;
  /**
   * Current selling price
   */
  price: number;
  /**
   * Original price (for showing discounts)
   */
  compareAtPrice?: number | null;
  /**
   * Track and manage product stock levels
   */
  inventoryManagement: {
    /**
     * Enable stock tracking for this product
     */
    trackInventory?: boolean | null;
    /**
     * Current stock quantity
     */
    stock: number;
    /**
     * Alert when stock falls below this
     */
    lowStockThreshold?: number | null;
    /**
     * Stock reserved for pending orders
     */
    reservedStock?: number | null;
    /**
     * Allow orders even when out of stock
     */
    allowBackorders?: boolean | null;
  };
  /**
   * Primary product image
   */
  image?: (number | null) | Media;
  /**
   * Additional product images
   */
  gallery?:
    | {
        image: number | Media;
        /**
         * Alt text for accessibility
         */
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Use this for placeholder images or external image URLs. Either image or imageUrl should be provided.
   */
  imageUrl?: string | null;
  /**
   * Enable if product comes in different sizes, colors, etc.
   */
  hasVariants?: boolean | null;
  /**
   * Add different sizes, colors, or other variations
   */
  variants?:
    | {
        /**
         * e.g., "Small - Red", "Large - Blue"
         */
        name: string;
        /**
         * Variant-specific SKU
         */
        sku?: string | null;
        size?: ('xs' | 's' | 'm' | 'l' | 'xl' | 'xxl' | 'free') | null;
        /**
         * e.g., Red, Blue, #FF0000
         */
        color?: string | null;
        /**
         * e.g., 250g, 500g, 1kg
         */
        weight?: string | null;
        /**
         * Override base price (optional)
         */
        price?: number | null;
        /**
         * Stock for this variant
         */
        stock: number;
        available?: boolean | null;
        /**
         * Variant-specific image (optional)
         */
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Product is available for purchase
   */
  available?: boolean | null;
  /**
   * Show this product in featured sections
   */
  featured?: boolean | null;
  category?: (number | null) | Category;
  /**
   * Tags for search and filtering (comma-separated)
   */
  tags?: string[] | null;
  /**
   * Products to show in "You may also like" section
   */
  relatedProducts?: (number | Item)[] | null;
  shipping?: {
    /**
     * Weight in grams
     */
    weight?: number | null;
    /**
     * This product ships free
     */
    freeShipping?: boolean | null;
    dimensions?: {
      /**
       * Length in cm
       */
      length?: number | null;
      /**
       * Width in cm
       */
      width?: number | null;
      /**
       * Height in cm
       */
      height?: number | null;
    };
  };
  /**
   * Search engine optimization settings
   */
  seo?: {
    /**
     * SEO title (defaults to product name if empty)
     */
    title?: string | null;
    /**
     * Meta description for search engines
     */
    description?: string | null;
    /**
     * URL-friendly slug (auto-generated if empty)
     */
    slug?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  user?: (number | null) | User;
  /**
   * Coupon applied to this order, if any
   */
  coupon?: (number | null) | Coupon;
  /**
   * Discount amount applied from coupon
   */
  discountAmount?: number | null;
  /**
   * Captured at order time
   */
  userAgent?: string | null;
  deviceType?: ('mobile' | 'desktop' | 'tablet' | 'other') | null;
  /**
   * Name captured at time of order
   */
  customerName: string;
  customerEmail: string;
  /**
   * Customer contact number captured at time of order
   */
  customerNumber: string;
  paymentMethod: 'cod' | 'bkash' | 'nagad';
  /**
   * Wallet number used to send the payment
   */
  paymentSenderNumber?: string | null;
  /**
   * Reference ID from the mobile wallet payment
   */
  paymentTransactionId?: string | null;
  items: {
    item: number | Item;
    quantity: number;
    id?: string | null;
  }[];
  /**
   * Current status of the order - updates customer via email notifications
   */
  status: 'pending' | 'processing' | 'shipped' | 'completed' | 'cancelled' | 'refunded';
  totalAmount: number;
  subtotal: number;
  shippingCharge: number;
  deliveryZone: 'inside_dhaka' | 'outside_dhaka';
  freeDeliveryApplied?: boolean | null;
  orderDate: string;
  /**
   * Shipping address captured at time of order
   */
  shippingAddress: {
    line1: string;
    line2?: string | null;
    city: string;
    state?: string | null;
    postalCode: string;
    country?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons".
 */
export interface Coupon {
  id: number;
  /**
   * Unique coupon code (e.g., SAVE10)
   */
  code: string;
  discountType: 'percent' | 'fixed';
  /**
   * Discount percentage (0-100 for percent) or fixed amount
   */
  discountValue: number;
  /**
   * Optional expiry date
   */
  expiryDate?: string | null;
  /**
   * Whether the coupon is currently active
   */
  isActive: boolean;
  /**
   * Maximum number of uses (0 for unlimited)
   */
  usageLimit?: number | null;
  /**
   * Number of times used (auto-updated)
   */
  usedCount?: number | null;
  applicableTo: 'all' | 'first_order';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  item: number | Item;
  /**
   * Reviewer (auto-set)
   */
  user: number | User;
  /**
   * Captured from user at time of review
   */
  reviewerName?: string | null;
  rating: number;
  title?: string | null;
  comment: string;
  approved: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "abandoned-carts".
 */
export interface AbandonedCart {
  id: number;
  /**
   * Anonymous session identifier for the cart
   */
  sessionId: string;
  user?: (number | null) | User;
  customerName?: string | null;
  customerEmail?: string | null;
  customerNumber?: string | null;
  items?:
    | {
        item: number | Item;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  cartTotal?: number | null;
  status: 'active' | 'abandoned' | 'recovered';
  /**
   * How many recovery reminder emails have been sent
   */
  reminderStage?: number | null;
  lastActivityAt: string;
  recoveredOrder?: (number | null) | Order;
  recoveryEmailSentAt?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Configure delivery charges and free delivery thresholds.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "delivery-settings".
 */
export interface DeliverySetting {
  id: number;
  label: string;
  insideDhakaCharge: number;
  outsideDhakaCharge: number;
  /**
   * Orders equal to or above this amount receive free delivery.
   */
  freeDeliveryThreshold: number;
  /**
   * Applied when the order total is below the free delivery threshold.
   */
  digitalPaymentDeliveryCharge: number;
  shippingHighlightTitle: string;
  shippingHighlightSubtitle: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  author: number | User;
  publishedDate: string;
  category: number | Category;
  featuredImage?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  excerpt?: string | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "program-participants".
 */
export interface ProgramParticipant {
  id: number;
  name: string;
  /**
   * 11-digit phone number
   */
  phone: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Browser push notification subscriptions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "push-subscriptions".
 */
export interface PushSubscription {
  id: number;
  /**
   * The user who owns this subscription
   */
  user: number | User;
  /**
   * Push service endpoint URL
   */
  endpoint: string;
  /**
   * Encryption keys for push notifications
   */
  keys: {
    /**
     * Public key for message encryption
     */
    p256dh: string;
    /**
     * Authentication secret
     */
    auth: string;
  };
  /**
   * Browser user agent for debugging
   */
  userAgent?: string | null;
  /**
   * Whether this subscription is still active
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * User wishlists for saving favorite products
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wishlists".
 */
export interface Wishlist {
  id: number;
  /**
   * The user who owns this wishlist
   */
  user: number | User;
  /**
   * Products saved to wishlist
   */
  items?:
    | {
        item: number | Item;
        /**
         * When this item was added to wishlist
         */
        addedAt?: string | null;
        /**
         * Notify user when this item goes on sale
         */
        notifyOnSale?: boolean | null;
        /**
         * Notify user when this item is back in stock
         */
        notifyOnStock?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Number of items in wishlist
   */
  itemCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'items';
        value: number | Item;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'abandoned-carts';
        value: number | AbandonedCart;
      } | null)
    | ({
        relationTo: 'delivery-settings';
        value: number | DeliverySetting;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'program-participants';
        value: number | ProgramParticipant;
      } | null)
    | ({
        relationTo: 'coupons';
        value: number | Coupon;
      } | null)
    | ({
        relationTo: 'push-subscriptions';
        value: number | PushSubscription;
      } | null)
    | ({
        relationTo: 'wishlists';
        value: number | Wishlist;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  customerNumber?: T;
  deliveryZone?: T;
  role?: T;
  firstName?: T;
  lastName?: T;
  address?:
    | T
    | {
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "items_select".
 */
export interface ItemsSelect<T extends boolean = true> {
  name?: T;
  sku?: T;
  shortDescription?: T;
  description?: T;
  price?: T;
  compareAtPrice?: T;
  inventoryManagement?:
    | T
    | {
        trackInventory?: T;
        stock?: T;
        lowStockThreshold?: T;
        reservedStock?: T;
        allowBackorders?: T;
      };
  image?: T;
  gallery?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  imageUrl?: T;
  hasVariants?: T;
  variants?:
    | T
    | {
        name?: T;
        sku?: T;
        size?: T;
        color?: T;
        weight?: T;
        price?: T;
        stock?: T;
        available?: T;
        image?: T;
        id?: T;
      };
  available?: T;
  featured?: T;
  category?: T;
  tags?: T;
  relatedProducts?: T;
  shipping?:
    | T
    | {
        weight?: T;
        freeShipping?: T;
        dimensions?:
          | T
          | {
              length?: T;
              width?: T;
              height?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        slug?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  user?: T;
  coupon?: T;
  discountAmount?: T;
  userAgent?: T;
  deviceType?: T;
  customerName?: T;
  customerEmail?: T;
  customerNumber?: T;
  paymentMethod?: T;
  paymentSenderNumber?: T;
  paymentTransactionId?: T;
  items?:
    | T
    | {
        item?: T;
        quantity?: T;
        id?: T;
      };
  status?: T;
  totalAmount?: T;
  subtotal?: T;
  shippingCharge?: T;
  deliveryZone?: T;
  freeDeliveryApplied?: T;
  orderDate?: T;
  shippingAddress?:
    | T
    | {
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  item?: T;
  user?: T;
  reviewerName?: T;
  rating?: T;
  title?: T;
  comment?: T;
  approved?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "abandoned-carts_select".
 */
export interface AbandonedCartsSelect<T extends boolean = true> {
  sessionId?: T;
  user?: T;
  customerName?: T;
  customerEmail?: T;
  customerNumber?: T;
  items?:
    | T
    | {
        item?: T;
        quantity?: T;
        id?: T;
      };
  cartTotal?: T;
  status?: T;
  reminderStage?: T;
  lastActivityAt?: T;
  recoveredOrder?: T;
  recoveryEmailSentAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "delivery-settings_select".
 */
export interface DeliverySettingsSelect<T extends boolean = true> {
  label?: T;
  insideDhakaCharge?: T;
  outsideDhakaCharge?: T;
  freeDeliveryThreshold?: T;
  digitalPaymentDeliveryCharge?: T;
  shippingHighlightTitle?: T;
  shippingHighlightSubtitle?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  author?: T;
  publishedDate?: T;
  category?: T;
  featuredImage?: T;
  content?: T;
  excerpt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "program-participants_select".
 */
export interface ProgramParticipantsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons_select".
 */
export interface CouponsSelect<T extends boolean = true> {
  code?: T;
  discountType?: T;
  discountValue?: T;
  expiryDate?: T;
  isActive?: T;
  usageLimit?: T;
  usedCount?: T;
  applicableTo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "push-subscriptions_select".
 */
export interface PushSubscriptionsSelect<T extends boolean = true> {
  user?: T;
  endpoint?: T;
  keys?:
    | T
    | {
        p256dh?: T;
        auth?: T;
      };
  userAgent?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wishlists_select".
 */
export interface WishlistsSelect<T extends boolean = true> {
  user?: T;
  items?:
    | T
    | {
        item?: T;
        addedAt?: T;
        notifyOnSale?: T;
        notifyOnStock?: T;
        id?: T;
      };
  itemCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}